//------------------------------------------------------------------------------
// <auto-generated>
// Este código fue generado por una herramienta.
// Versión de tiempo de ejecución: 4.0.30319.42000
//
// Los cambios en el archivo pueden causar un comportamiento incorrecto y se perderán si
// se recrea el código
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Calculator.Properties
{


    /// <summary>
    /// Una clase de recurso fuertemente tipada, para buscar cadenas localizadas, etc.
    /// </summary>
    // Esta clase fue generada automáticamente por StronglyTypedResourceBuilder
    // clase a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o eliminar un asociado, edite el archivo .ResX y vuelva a ejecutar ResGen
    // con la opción /str o reconstruir su proyecto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Devuelve la instancia almacenada en caché de ResourceManager utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF_Calculator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Anula la propiedad CurrentUICulture del subproceso actual para todos
        /// búsquedas de recursos que utilizan esta clase de recurso fuertemente tipada
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}
